apiVersion: apps/v1
kind: Deployment
metadata:
  name: galasa-ecosystem-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: galasa-ecosystem-operator
  template:
    metadata:
      labels:
        name: galasa-ecosystem-operator
    spec:
      serviceAccountName: galasa-ecosystem-operator
      containers:
        - name: galasa-ecosystem-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - galasa-ecosystem-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "galasa-ecosystem-operator"
