apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: galasaecosystems.galasa.dev
spec:
  group: galasa.dev
  names:
    kind: GalasaEcosystem
    listKind: GalasaEcosystemList
    plural: galasaecosystems
    singular: galasaecosystem
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: GalasaEcosystem is the Schema for the galasaecosystems API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: GalasaEcosystemSpec defines the desired state of GalasaEcosystem
            properties:
              propertystore:
                description: PropertyStoreCluster spec for the CPS cluster
                properties:
                  init_props:
                    description: Any additional properties to be added to the CPS
                      upon initialization
                    items:
                      type: string
                    type: array
                  property_cluster_size:
                    description: This size of the etcd cluster which hosts the CPS
                      and DSS Default size is 1
                    format: int32
                    type: integer
                  replicas:
                    description: Number of replicas
                    format: int32
                    type: integer
                  resources:
                    description: Optional
                    properties:
                      limits:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Limits describes the maximum amount of compute
                          resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                        type: object
                      requests:
                        additionalProperties:
                          anyOf:
                          - type: integer
                          - type: string
                          pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                          x-kubernetes-int-or-string: true
                        description: 'Requests describes the minimum amount of compute
                          resources required. If Requests is omitted for a container,
                          it defaults to Limits if that is explicitly specified, otherwise
                          to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                        type: object
                    type: object
                type: object
            required:
            - propertystore
            type: object
          status:
            description: GalasaEcosystemStatus defines the observed state of GalasaEcosystem
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
